# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: example-templates
builds:
  - env:
      - CGO_ENABLED=0
    goarch: [ amd64 ]
    goos:
      - linux
      - darwin

templates:
  - src: ''
    dst: blah
  - src: .github/release.tpl.sh
    dst: release.sh
    mode: 0755
  - src: 'aaa'
    dst: ''

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
